- name: Download Maven
  get_url:  ### wget url -O /tmp/tomca.tgz
    url: https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz
    dest: /tmp/apache-maven-3.8.5-bin.tar.gz

- name: Extract archive
  shell: /bin/tar xvf /tmp/apache-maven-3.8.5-bin.tar.gz -C /opt

- name: Update mvn command
  shell: /usr/bin/update-alternatives --install /usr/bin/mvn maven /opt/apache-maven-3.8.5/bin/mvn 1001
