- name: Download Tomcat
  get_url:  ### wget url -O /tmp/tomca.tgz
    url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40.tar.gz
    dest: /tmp/apache-tomcat-8.5.40.tar.gz

- name: Extract archive
  shell: /bin/tar xvf /tmp/apache-tomcat-8.5.40.tar.gz -C /opt

- name: create Symlink
  file:
    src: /opt/apache-tomcat-8.5.40
    path: /opt/tomcat
    owner: tomcat
    group: tomcat
    state: link

- name: Change ownership of Tomcat installation
  file:
    path: /opt/tomcat/
    owner: tomcat
    group: tomcat
    mode: 0755
    state: directory
    recurse: yes

- name: create tomcat.service file
  file:
    path: /etc/systemd/system/tomcat.service
    state: touch

- name: create tomcat service
  blockinfile:
    path: /etc/systemd/system/tomcat.service
    block: |
      [Unit]
      Description=Tomcat - instance %i
      After=syslog.target network.target
      [Service]
      Type=forking
      User=tomcat
      Group=tomcat
      Environment="CATALINA_HOME=/opt/tomcat/"
      ExecStart=/opt/tomcat/bin/startup.sh
      ExecStop=/opt/tomcat/bin/shutdown.sh
      [Install]
      WantedBy=multi-user.target
- name: enable & start tomcat service
  systemd:
    name: tomcat
    state: started
    enabled: yes

- name: validate tomcat is running
  shell: service tomcat status
  register: tstatus

- debug:
    var: tstatus.stdout_lines 
